### ISSUE TITLE
Error in REST_API_URL in docker-compose.override.yml

### ISSUE THREAD

**Issue by beastarman74** [snypy/snypy-docker#14]
The override yaml file has the REST_API_URL appended with /api/v1/.  When attempting to register a user or login. The below errors are generated in the API container log. 

- Not Found: /api/v1//api/v1/auth/register/

- Not Found: /api/v1//api/v1/auth/token/login/

I assume the /api/v1/ is appended automatically now and no longer needs to be stated in the REST_API_URL?

Removing the /api/v1/ from the REST_API_URL in the override.yml file gets the app working. 

Let me know if you need any further information on this.

**Comment by nezhar** [comment]
Sorry for that, I already created a PR to fix this in the setup. This is part of the release `1.1.0` published yesterday where we included our new data access module via https://github.com/snypy/snypy-frontend/pull/1199

The REST_API_URL will no longer require the `/api/v1` sufix as this is already included via OpenAPI and generated in our rest client https://www.npmjs.com/package/@snypy/rest-client
