### ISSUE TITLE
Frontend container wrong port

### ISSUE THREAD

**Issue by GhaziTriki** [snypy/snypy-docker#16]
Hello,

The frontend is listening to port 80 not 8080.

Thanks

**Comment by nezhar** [comment]
Hi, not sure to what this reffers exactly, the internal port of the nginx container is `80` but in the docs `8080` is the external port which forwards to `80`. If there is any typo in the docs you can always open a PR :wink:

**Comment by GhaziTriki** [comment]
Hi @nezhar,

I have a working docker-compose.yml that I will share soon.

**Comment by norweeg** [comment]
@nezhar this should be reopened.  your example compose file and example for nginx config show the ui container listening on port 8080, but the configuration for that container is having the server listen on port 80.
