### ISSUE TITLE
The description and development are not clear and we don't understand composes.

### ISSUE THREAD

**Issue by JuanRodenas** [snypy/snypy-docker#18]
Hello,

I've been trying to figure out how the docker-compose you have in the repository work.
Can you tell us the steps to follow? The description and development are not clear and we don't understand composes.

Best regards,
Juan.

**Comment by nezhar** [comment]
There is a quick setup guide in the readme https://github.com/snypy/snypy-docker#setup-application

Can you detail where you exactly have issues with the setup? I'm glad to use your input in order to extend the guide.

**Comment by JuanRodenas** [comment]
Hello!

I have created a container with this data:
* Creates an override file based on the dev configuration: `cp docker-compose.override.dev.yml docker-compose.override.yml`.
* Clone the rest API code: `git clone https://github.com/snypy/snypy-backend.git code/snypy-backend`.
* Run docker compose: `docker-compose up

Can you detail the steps better?
I can't access the service.

Best regards

**Comment by ztobs** [comment]
Get solution to your new issue here: `https://github.com/snypy/snypy-docker/issues/17`

**Comment by nezhar** [comment]
@JuanRodenas The steps in the readme are now extended, can you try it one more time?
