### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by Monkey999Human** [snypy/snypy-docker#21]
I am writing to inform you about an issue I am facing with setting up the snypy-docker instance of your program. I have been attempting to get it up and running for the past hour, but unfortunately, I have been unsuccessful so far. I am really excited to use your program and would greatly appreciate your assistance in resolving this problem.

I have attempted two different methods to deploy the program: using manual commands with Docker Compose and trying it through Portainer. Regrettably, neither approach has yielded the desired results. The program is still not functioning correctly, and I am unsure what steps to take next.

In light of this, I wanted to inquire if it would be possible for you to provide a file that I can include in a stack deployment for Portainer. Having a preconfigured file would simplify the deployment process and ensure the correct setup for your program. It would be particularly helpful if you could incorporate variables that can be easily filled in, allowing for easier customization and configuration during the deployment process.

Additionally, I would like to know if there is a way to view the open ports in Portainer once the program is deployed. Having this information would be immensely helpful for troubleshooting and for visual comfort.

I apologize for any inconvenience caused by this support ticket, and I appreciate your prompt attention to this matter. Thank you in advance for your assistance. Please let me know if there are any further details or logs that I can provide to help diagnose the issue.

Looking forward to your response.

**Comment by juanyunis** [comment]
If you still have problems trying to make it work, I was successfully able to run it. I did have to create a better docker-compose.yml that is 100% compatible with Portainer. Please see attached YAML file for portainer and also .env file that you can load with portainer. You have to modify the env vars with your desired values.

1. [https://pastebin.com/jbVNn1BM](url)
2. [https://pastebin.com/CtswVbPD](url)

Once you are successfully able to create the stack/containers, please login into the api console (using portainer or docker) and create a file in fixtures folder named setup.json and copy the contents from this url [https://raw.githubusercontent.com/snypy/snypy-docker/main/data/fixtures/setup.json](url) and then run: 
`python manage.py loaddata fixtures/setup.json`

After doing this you should be able to login into the admin panel with:
`username: admin
password: 12345678!`

**Comment by pommetjehorlepiep** [comment]
> If you still have problems trying to make it work, I was successfully able to run it. I did have to create a better docker-compose.yml that is 100% compatible with Portainer. Please see attached YAML file for portainer and also .env file that you can load with portainer. You have to modify the env vars with your desired values.
> 
> 1. [Portainer docker-compose.yml](https://pastebin.com/yLRmhUYs)
> 2. [Portainer .env file that you can load/import while creating the stack](https://pastebin.com/gex5rYMA)
> 
> Once you are successfully able to create the stack/containers, please login into the api console (using portainer or docker) and create a file in fixtures folder named setup.json and copy the contents from this url [setup.json fixture](https://raw.githubusercontent.com/snypy/snypy-docker/main/data/fixtures/setup.json) and then run: `python manage.py loaddata fixtures/setup.json`
> 
> After doing this you should be able to login into the admin panel with: `username: admin password: 12345678!`

@juanyunis the FRONTEND_URL & BACKEND_URL in the [.env file](https://pastebin.com/gex5rYMA) are swapped around I think...

Correct values should be:
> BACKEND_URL=https://api-my-domain.com 
> FRONTEND_URL=https://my-domain.com

**Comment by nezhar** [comment]
I would really appreaciate if you can directly do a pull request in future. I may consider adding the migrations on startup, maybe with a custom entrypoint script.

**Comment by nezhar** [comment]
The setup has fewer steps now, you should retry it.
