### ISSUE TITLE
Why exactly do we need to do things to run this application?

### ISSUE THREAD

**Issue by zunjae** [snypy/snypy-docker#31]
I've been using Docker with Compose for many years now and noticed this is the _first_ project EVER where we manually have to do things such as migrating the database.

Considering it's 2024 (and not the 90's) I was wondering why these manual steps are required?

Why can't this be part of the application or docker setup?

**Comment by nezhar** [comment]
Since this is an open repository, you are always welcome to create a PR.

**Comment by nezhar** [comment]
I's a workflow decision at the end of the day, and it's not always that easy to cover it.

I give it a try in https://github.com/snypy/snypy-docker/pull/33, and this is going to be integrated in the reposiotry, and it is going to be used starting `1.5.0`
